WebNotas/Controllers/DesarrolloController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebNotas.Models;

namespace WebNotas.Controllers
{
    public class DesarrolloController : Controller
    {
        public IActionResult Index()
        {
            return View("Folleto");
        }
        public IActionResult Folleto()
        {
            return View();
        }
        public IActionResult Primero()
        {
            return View();
        }
        public IActionResult Segundo()
        {
            return View();
        }
        public IActionResult Tercero()
        {
            return View();
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebNotas/Controllers/InfraestructuraController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebNotas.Controllers
{
    public class InfraestructuraController : Controller
    {
        public IActionResult Index()
        {
            return View("Folleto");
        }
        public IActionResult Folleto()
        {
            return View();
        }
        public IActionResult Primero() 
        {
            ViewData["Año"] = "Primer año";
            ViewData["Materias"] = new string[] { "Comunicación (1° cuat.)", "Unidad de definición Institucional (2° cuat.)", "Matemática", "Física Aplicada a las Tecnologías de la Información", "Administración ", "Inglés Técnico ", "Arquitectura de las Computadoras", "Lógica y Programación  ", "Infraestructura de Redes I" };
            return View("Materias");
        }
        public IActionResult Segundo()
        {
            ViewData["Año"] = "Segundo año";
            ViewData["Materias"] = new string[] { "Problemáticas Socio Contemporáneas (1° cuat.)Unidad de definición Institucional (2° cuat.)","Innovación y Desarrollo Emprendedor","Estadística","Sistemas Operativos","Algoritmos y Estructuras de Datos ","Base de Datos ","Infraestructura de Datos II ","Práctica Profesionalizante I" };
            return View("Materias");
        }
        public IActionResult Tercero()
        {
            ViewData["Año"] = "Tercer año";
            ViewData["Materias"] = new string[] { "Ética y Responsabilidad Social","Derecho y Legislación Laboral ","Administración de Base de Datos ","Integridad y Migración de Datos ","Seguridad de los Sistemas ","Administración de Sistemas ","Operativos y Redes ","Práctica Profesionalizante II " };
            return View("Materias");
        }
    }
}

WebNotas/Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebNotas.Models;

namespace WebNotas.Controllers
{
    public class NotasController : Controller
    {
        private readonly WebNotasContext _context;

        public NotasController(WebNotasContext context)
        {
            _context = context;
        }

        // GET: Notas
        public async Task<IActionResult> Index()
        {
              return _context.Notas != null ? 
                          View(await _context.Notas.ToListAsync()) :
                          Problem("Entity set 'WebNotasContext.Notas'  is null.");
        }

        // GET: Notas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // GET: Notas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Contenido,Imagen")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nota);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nota);
        }

        // GET: Notas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas.FindAsync(id);
            if (nota == null)
            {
                return NotFound();
            }
            return View(nota);
        }

        // POST: Notas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Contenido,Imagen")] Nota nota)
        {
            if (id != nota.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotaExists(nota.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nota);
        }

        // GET: Notas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // POST: Notas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notas == null)
            {
                return Problem("Entity set 'WebNotasContext.Notas'  is null.");
            }
            var nota = await _context.Notas.FindAsync(id);
            if (nota != null)
            {
                _context.Notas.Remove(nota);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotaExists(int id)
        {
          return (_context.Notas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebNotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebNotas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebNotas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebNotas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Autor">Autor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SitioIsp20">Sitio ISP20</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Notas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Notas" asp-action="Index">Lista de notas</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Notas" asp-action="Create">Crear una nueva nota</a></li>

                                

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Nuestra Carrera
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Desarrollo" asp-action="Folleto">Folleto</a></li>
                                <li><hr class="dropdown-divider"></li>       
                                <li><a class="dropdown-item" asp-controller="Desarrollo" asp-action="Primero">Materias 1º Año</a></li>
                                                                             
                                <li><a class="dropdown-item" asp-controller="Desarrollo" asp-action="Segundo">Materias 2º Año</a></li>
                                <li><a class="dropdown-item" asp-controller="Desarrollo" asp-action="Tercero">Materias 3º Año</a></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Tec.Sup. de Soporte en Infraestructura
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Infraestructura" asp-action="Folleto">Folleto</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Infraestructura" asp-action="Primero">Materias 1º Año</a></li>

                                <li><a class="dropdown-item" asp-controller="Infraestructura" asp-action="Segundo">Materias 2º Año</a></li>
                                <li><a class="dropdown-item" asp-controller="Infraestructura" asp-action="Tercero">Materias 3º Año</a></li>

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebNotas - ISP20 <a asp-area="" asp-controller="Home" asp-action="Autor">Autor</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>